# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "as9737-32db-layer"
BBFILE_PATTERN_as9737-32db-layer := "^${LAYERDIR}/"
LAYERSERIES_COMPAT_as9737-32db-layer = "warrior zeus dunfell"
